
import { useState } from "react";
import { AdminLayout } from "@/components/admin/AdminLayout";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Textarea } from "@/components/ui/textarea";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";
import { useCustomCode, CustomCode } from "@/components/admin/custom-code/useCustomCode";

const AdminCustomCode = () => {
  const { customCodeList, saveCustomCode, isLoading } = useCustomCode();
  const [name, setName] = useState("");
  const [htmlCode, setHtmlCode] = useState("");
  const [cssCode, setCssCode] = useState("");
  const [jsCode, setJsCode] = useState("");
  const [location, setLocation] = useState<string>("global");
  const [isPublished, setIsPublished] = useState(false);
  const [activeTab, setActiveTab] = useState("html");

  const handleSave = async () => {
    if (!name.trim()) {
      alert("يرجى إدخال اسم للكود");
      return;
    }

    const codeToSave: CustomCode = {
      code_id: "",  // New code, will be generated by the server
      name: name,
      html_code: htmlCode,
      css_code: cssCode,
      js_code: jsCode,
      location: location,
      is_published: isPublished,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    };

    await saveCustomCode(codeToSave);
    
    // Reset form
    setName("");
    setHtmlCode("");
    setCssCode("");
    setJsCode("");
    setLocation("global");
    setIsPublished(false);
  };

  return (
    <AdminLayout>
      <div className="space-y-6">
        <h2 className="text-3xl font-bold tracking-tight">أكواد إضافية</h2>
        <Card>
          <CardHeader>
            <CardTitle>أكواد مخصصة</CardTitle>
            <CardDescription>إضافة أكواد HTML أو CSS أو JavaScript مخصصة للموقع</CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="space-y-2">
              <Label htmlFor="code-name">اسم الكود</Label>
              <Input 
                id="code-name" 
                placeholder="أدخل اسمًا وصفيًا للكود" 
                value={name} 
                onChange={(e) => setName(e.target.value)} 
              />
            </div>
            
            <div className="space-y-2">
              <Label>موقع الكود</Label>
              <Select value={location} onValueChange={setLocation}>
                <SelectTrigger>
                  <SelectValue placeholder="اختر موقع الكود" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="global">جميع الصفحات</SelectItem>
                  <SelectItem value="header">رأس الصفحة</SelectItem>
                  <SelectItem value="footer">تذييل الصفحة</SelectItem>
                  <SelectItem value="home">الصفحة الرئيسية فقط</SelectItem>
                </SelectContent>
              </Select>
            </div>
            
            <div className="flex items-center space-x-2">
              <Switch 
                id="publish-code" 
                checked={isPublished}
                onCheckedChange={setIsPublished} 
              />
              <Label htmlFor="publish-code">نشر الكود</Label>
            </div>
            
            <Tabs value={activeTab} onValueChange={setActiveTab}>
              <TabsList className="grid w-full grid-cols-3">
                <TabsTrigger value="html">HTML</TabsTrigger>
                <TabsTrigger value="css">CSS</TabsTrigger>
                <TabsTrigger value="js">JavaScript</TabsTrigger>
              </TabsList>
              
              <TabsContent value="html">
                <div className="space-y-2">
                  <Label htmlFor="html-code">أكواد HTML</Label>
                  <Textarea 
                    id="html-code" 
                    placeholder="أضف أكواد HTML هنا..." 
                    className="min-h-[250px] font-mono" 
                    value={htmlCode}
                    onChange={(e) => setHtmlCode(e.target.value)}
                  />
                </div>
              </TabsContent>
              
              <TabsContent value="css">
                <div className="space-y-2">
                  <Label htmlFor="css-code">أكواد CSS</Label>
                  <Textarea 
                    id="css-code" 
                    placeholder="أضف أكواد CSS هنا..." 
                    className="min-h-[250px] font-mono"
                    value={cssCode}
                    onChange={(e) => setCssCode(e.target.value)}
                  />
                </div>
              </TabsContent>
              
              <TabsContent value="js">
                <div className="space-y-2">
                  <Label htmlFor="js-code">أكواد JavaScript</Label>
                  <Textarea 
                    id="js-code" 
                    placeholder="أضف أكواد JavaScript هنا..." 
                    className="min-h-[250px] font-mono"
                    value={jsCode}
                    onChange={(e) => setJsCode(e.target.value)}
                  />
                </div>
              </TabsContent>
            </Tabs>
            
            <div className="flex justify-end">
              <Button onClick={handleSave} disabled={isLoading}>حفظ الأكواد</Button>
            </div>
          </CardContent>
        </Card>
        
        {customCodeList.length > 0 && (
          <Card>
            <CardHeader>
              <CardTitle>الأكواد المحفوظة</CardTitle>
              <CardDescription>قائمة بجميع الأكواد المخصصة المحفوظة</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="space-y-4">
                {customCodeList.map((code) => (
                  <div key={code.code_id} className="p-4 border rounded-md">
                    <div className="flex justify-between items-center">
                      <h3 className="font-bold">{code.name}</h3>
                      <span className={`px-2 py-1 text-xs rounded ${code.is_published ? 'bg-green-100 text-green-800' : 'bg-gray-100 text-gray-800'}`}>
                        {code.is_published ? 'منشور' : 'غير منشور'}
                      </span>
                    </div>
                    <p className="text-sm text-gray-500 mt-1">{code.location || 'global'}</p>
                    <div className="mt-2 flex gap-2">
                      <Button variant="outline" size="sm">تعديل</Button>
                      <Button variant="destructive" size="sm">حذف</Button>
                    </div>
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>
        )}
      </div>
    </AdminLayout>
  );
};

export default AdminCustomCode;
