// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mbgxvblbydwshgelunfa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1iZ3h2YmxieWR3c2hnZWx1bmZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyMDA3OTMsImV4cCI6MjA1OTc3Njc5M30.9mv41kboKk3Jg22OKjxJ0BTq4CJD-eHqppGbVtCQKLw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);